In [20]:
import pandas as pd

In [21]:
veri = pd.read_csv("playlist_dataset(lyrics)_new_kopyası.csv")

In [22]:
veri.head()

,Track Name,Artist,Artist URI,Artist Popularity,Artist Genres,Track Duration(ms),Release Date,Track Popularity,Danceability,Energy,...,Valence,Tempo,Type,Track ID,Uri,Track_href,Analysis_url,Duration_ms,Time_signature,Lyrics
0,"yes, and?",Ariana Grande,spotify:artist:66CXWjxzNUsdJxJ2JdwvnR,89,pop,214994,2024-01-12,96,0.788,0.758,...,0.823,119.008,audio_features,7gaA3wERFkFkgivjwbSvkG,spotify:track:7gaA3wERFkFkgivjwbSvkG,https://api.spotify.com/v1/tracks/7gaA3wERFkFk...,https://api.spotify.com/v1/audio-analysis/7gaA...,214994,4,"In case you haven't noticed\nWell, everybody's..."
1,Snooze,SZA,spotify:artist:7tYKF4w9nC0nq9CsPZTHyP,90,"pop, r&b, rap",201800,2022-12-09,94,0.559,0.551,...,0.392,143.008,audio_features,4iZ4pt7kvcaH6Yo8UoZ4s2,spotify:track:4iZ4pt7kvcaH6Yo8UoZ4s2,https://api.spotify.com/v1/tracks/4iZ4pt7kvcaH...,https://api.spotify.com/v1/audio-analysis/4iZ4...,201800,4,I'll touch that fire for you\nI do that three-...
2,Die For You - Remix,The Weeknd,spotify:artist:1Xyo4u8uXC1ZmMpatF05PJ,95,"canadian contemporary r&b, canadian pop, pop",232857,2023-02-24,82,0.531,0.525,...,0.502,66.900,audio_features,7oDd86yk8itslrA9HRP2ki,spotify:track:7oDd86yk8itslrA9HRP2ki,https://api.spotify.com/v1/tracks/7oDd86yk8its...,https://api.spotify.com/v1/audio-analysis/7oDd...,232857,4,I'm findin' ways to articulate the feelin' I'm...
3,Stick Season,Noah Kahan,spotify:artist:2RQXRUsr4IW1f3mKyKsy4B,87,pov: indie,182346,2022-10-14,98,0.662,0.488,...,0.817,117.913,audio_features,0mflMxspEfB0VbI1kyLiAv,spotify:track:0mflMxspEfB0VbI1kyLiAv,https://api.spotify.com/v1/tracks/0mflMxspEfB0...,https://api.spotify.com/v1/audio-analysis/0mfl...,182347,4,As you promised me that I was more than all th...
4,vampire,Olivia Rodrigo,spotify:artist:1McMsnEElThX1knmY4oliG,88,pop,219724,2023-06-30,37,0.511,0.532,...,0.322,137.827,audio_features,3k79jB4aGmMDUQzEwa46Rz,spotify:track:3k79jB4aGmMDUQzEwa46Rz,https://api.spotify.com/v1/tracks/3k79jB4aGmMD...,https://api.spotify.com/v1/audio-analysis/3k79...,219724,4,"I hate to give the satisfaction asking, ""How y..."

In [23]:
print(veri)

                                         Track Name            Artist  \
0                                         yes, and?     Ariana Grande
1                                            Snooze               SZA
2                               Die For You - Remix        The Weeknd
3                                      Stick Season        Noah Kahan
4                                           vampire    Olivia Rodrigo
...                                             ...               ...
1136                                     Miles Away       Krysta Nick
1137  half of my hometown - ballerini album version  Kelsea Ballerini
1138                                 Suitcase Heart        Tyler Cain
1139                                      St. Louis        David Nail
1140                                      Heartland   Hailey Whitters

                                 Artist URI  Artist Popularity  \
0     spotify:artist:66CXWjxzNUsdJxJ2JdwvnR                 89
1     spotify:artist:7tYKF4w9nC0nq9CsPZTHyP                 90
2     spotify:artist:1Xyo4u8uXC1ZmMpatF05PJ                 95
3     spotify:artist:2RQXRUsr4IW1f3mKyKsy4B                 87
4     spotify:artist:1McMsnEElThX1knmY4oliG                 88
...                                     ...                ...
1136  spotify:artist:3hld0M8pAutQUblD6tI1ol                 22
1137  spotify:artist:3RqBeV12Tt7A8xH3zBDDUF                 68
1138  spotify:artist:7xmVA0jnh2yjM3S642J1Bd                 31
1139  spotify:artist:4DZGvSv2oMkBUnPz67E6z6                 49
1140  spotify:artist:4e9TBaTlI3LVQz3tkTYC0I                 56

                                          Artist Genres  Track Duration(ms)  \
0                                                   pop              214994
1                                         pop, r&b, rap              201800
2          canadian contemporary r&b, canadian pop, pop              232857
3                                            pov: indie              182346
4                                                   pop              219724
...                                                 ...                 ...
1136                                                NaN              220000
1137                      contemporary country, country              236226
1138                                                NaN              164194
1139  contemporary country, country road, modern cou...              274964
1140  contemporary country, country pop, modern coun...              211293

     Release Date  Track Popularity  Danceability  Energy  ...  Valence  \
0      2024-01-12                96         0.788   0.758  ...    0.823
1      2022-12-09                94         0.559   0.551  ...    0.392
2      2023-02-24                82         0.531   0.525  ...    0.502
3      2022-10-14                98         0.662   0.488  ...    0.817
4      2023-06-30                37         0.511   0.532  ...    0.322
...           ...               ...           ...     ...  ...      ...
1136   2015-12-16                42         0.546   0.490  ...    0.373
1137   2020-09-11                42         0.588   0.253  ...    0.221
1138   2017-11-15                42         0.757   0.290  ...    0.226
1139   2021-11-05                42         0.624   0.335  ...    0.324
1140   2021-02-26                41         0.622   0.671  ...    0.240

        Tempo            Type                Track ID  \
0     119.008  audio_features  7gaA3wERFkFkgivjwbSvkG
1     143.008  audio_features  4iZ4pt7kvcaH6Yo8UoZ4s2
2      66.900  audio_features  7oDd86yk8itslrA9HRP2ki
3     117.913  audio_features  0mflMxspEfB0VbI1kyLiAv
4     137.827  audio_features  3k79jB4aGmMDUQzEwa46Rz
...       ...             ...                     ...
1136  161.743  audio_features  0QnOPRxrCRLeRUEJKqecaG
1137  137.180  audio_features  3YJOCGSlrb78vNwu6meBSf
1138  123.004  audio_features  4GpT0HK2Gwuu4qiNlWW78L
1139   69.517  audio_features  3J8QHat7k7nfLwjjece9Ux
1140   79.971  audio_features  5o0hAYrXcdGYUlDC8j3x34

                                       Uri  \
0     spotify:track:7gaA3wERFkFkgivjwbSvkG
1     spotify:track:4iZ4pt7kvcaH6Yo8UoZ4s2
2     spotify:track:7oDd86yk8itslrA9HRP2ki
3     spotify:track:0mflMxspEfB0VbI1kyLiAv
4     spotify:track:3k79jB4aGmMDUQzEwa46Rz
...                                    ...
1136  spotify:track:0QnOPRxrCRLeRUEJKqecaG
1137  spotify:track:3YJOCGSlrb78vNwu6meBSf
1138  spotify:track:4GpT0HK2Gwuu4qiNlWW78L
1139  spotify:track:3J8QHat7k7nfLwjjece9Ux
1140  spotify:track:5o0hAYrXcdGYUlDC8j3x34

                                             Track_href  \
0     https://api.spotify.com/v1/tracks/7gaA3wERFkFk...
1     https://api.spotify.com/v1/tracks/4iZ4pt7kvcaH...
2     https://api.spotify.com/v1/tracks/7oDd86yk8its...
3     https://api.spotify.com/v1/tracks/0mflMxspEfB0...
4     https://api.spotify.com/v1/tracks/3k79jB4aGmMD...
...                                                 ...
1136  https://api.spotify.com/v1/tracks/0QnOPRxrCRLe...
1137  https://api.spotify.com/v1/tracks/3YJOCGSlrb78...
1138  https://api.spotify.com/v1/tracks/4GpT0HK2Gwuu...
1139  https://api.spotify.com/v1/tracks/3J8QHat7k7nf...
1140  https://api.spotify.com/v1/tracks/5o0hAYrXcdGY...

                                           Analysis_url  Duration_ms  \
0     https://api.spotify.com/v1/audio-analysis/7gaA...       214994
1     https://api.spotify.com/v1/audio-analysis/4iZ4...       201800
2     https://api.spotify.com/v1/audio-analysis/7oDd...       232857
3     https://api.spotify.com/v1/audio-analysis/0mfl...       182347
4     https://api.spotify.com/v1/audio-analysis/3k79...       219724
...                                                 ...          ...
1136  https://api.spotify.com/v1/audio-analysis/0QnO...       220000
1137  https://api.spotify.com/v1/audio-analysis/3YJO...       236227
1138  https://api.spotify.com/v1/audio-analysis/4GpT...       164195
1139  https://api.spotify.com/v1/audio-analysis/3J8Q...       274964
1140  https://api.spotify.com/v1/audio-analysis/5o0h...       211293

      Time_signature                                             Lyrics
0                  4  In case you haven't noticed\nWell, everybody's...
1                  4  I'll touch that fire for you\nI do that three-...
2                  4  I'm findin' ways to articulate the feelin' I'm...
3                  4  As you promised me that I was more than all th...
4                  4  I hate to give the satisfaction asking, "How y...
...              ...                                                ...
1136               4  It started out heading south on the PCH\nWindi...
1137               4  Half of my high school got too drunk\nHalf of ...
1138               4  Lying in your bed\nCan almost rest my head\nI ...
1139               4  I can hear the crowd\nThe sea of red\nMy favor...
1140               4  I should be married by now\nTwo kids in a paid...

[1141 rows x 27 columns]

In [24]:
veri.describe()

,Artist Popularity,Track Duration(ms),Track Popularity,Danceability,Energy,Key,Loudness,Mode,Speechiness,Acousticness,Instrumentalness,Liveness,Valence,Tempo,Duration_ms,Time_signature
count,1141.000000,1141.000000,1141.000000,1141.000000,1141.000000,1141.000000,1141.000000,1141.000000,1141.000000,1141.000000,1141.000000,1141.000000,1141.000000,1141.000000,1141.000000,1141.000000
mean,77.786152,207682.829974,73.770377,0.642325,0.624135,4.980719,-6.700345,0.633655,0.084448,0.248595,0.015284,0.165820,0.488953,120.712520,207700.540754,3.939527
std,12.851917,45521.286882,19.941358,0.146088,0.177323,3.680624,2.613393,0.482017,0.085306,0.268017,0.081971,0.122979,0.232185,28.506656,45462.649296,0.317373
min,22.000000,91554.000000,0.000000,0.122000,0.056200,0.000000,-18.439000,0.000000,0.022700,0.000013,0.000000,0.026400,0.037100,65.043000,91555.000000,1.000000
25%,71.000000,178360.000000,69.000000,0.546000,0.525000,1.000000,-7.930000,0.000000,0.034700,0.036800,0.000000,0.093800,0.309000,98.596000,178427.000000,4.000000
50%,80.000000,204033.000000,80.000000,0.650000,0.639000,5.000000,-6.181000,1.000000,0.048500,0.136000,0.000002,0.117000,0.478000,119.957000,204033.000000,4.000000
75%,87.000000,232373.000000,87.000000,0.750000,0.758000,8.000000,-4.920000,1.000000,0.090100,0.382000,0.000126,0.185000,0.656000,140.002000,232187.000000,4.000000
max,100.000000,613026.000000,99.000000,0.967000,0.987000,11.000000,-1.385000,1.000000,0.512000,0.978000,0.931000,0.874000,0.972000,205.863000,613027.000000,5.000000

In [26]:
veri_seti = pd.read_csv('playlist_dataset(lyrics)_new_kopyası.csv')

# Tekrarlanan satırları sil
temiz_veri_seti = veri.drop_duplicates()

# Sonucu yeni bir CSV dosyasına yaz
temiz_veri_seti.to_csv('temizlenmis_dosya_adı.csv', index=False)
temiz_veri_seti = temiz_veri_seti.sort_values(by='Track Name')

In [27]:
temiz_veri_seti.head()

,Track Name,Artist,Artist URI,Artist Popularity,Artist Genres,Track Duration(ms),Release Date,Track Popularity,Danceability,Energy,...,Valence,Tempo,Type,Track ID,Uri,Track_href,Analysis_url,Duration_ms,Time_signature,Lyrics
326,(It Goes Like) Nanana - Edit,Peggy Gou,spotify:artist:2mLA48B366zkELXYx7hcDN,69,"electra, float house",231545,2023-06-15,88,0.671,0.876,...,0.964,129.998,audio_features,23RoR84KodL5HWvUTneQ1w,spotify:track:23RoR84KodL5HWvUTneQ1w,https://api.spotify.com/v1/tracks/23RoR84KodL5...,https://api.spotify.com/v1/audio-analysis/23Ro...,231545,4,"I can't explain, I got a feeling that I just\n..."
775,02.02.99,That Mexican OT,spotify:artist:3BAgmPNIK5IJl7zMK1wvMA,71,texas latin rap,162162,2024-01-09,76,0.840,0.629,...,0.564,148.125,audio_features,582YxhgpJEY0aEHQtVQFhO,spotify:track:582YxhgpJEY0aEHQtVQFhO,https://api.spotify.com/v1/tracks/582YxhgpJEY0...,https://api.spotify.com/v1/audio-analysis/582Y...,162162,4,"(Skelez, oh, my God)\n\nCan't nobody tell me s..."
972,1st of Tha Month,Bone Thugs-N-Harmony,spotify:artist:5spEJXLwD1sKUdC2bnOHPg,65,"gangster rap, hardcore hip hop, hip hop, ohio ...",314680,1995-07-25,69,0.729,0.581,...,0.508,74.038,audio_features,1dF5Y2dd7Wm4wZKvVjWBpr,spotify:track:1dF5Y2dd7Wm4wZKvVjWBpr,https://api.spotify.com/v1/tracks/1dF5Y2dd7Wm4...,https://api.spotify.com/v1/audio-analysis/1dF5...,314680,4,"Wake up, wake up, wake up, wake up, wake up (i..."
1098,2016,Sam Hunt,spotify:artist:2kucQ9jQwuD8jWdtR9Ef38,68,"contemporary country, country, country pop, mo...",235053,2020-04-03,54,0.520,0.384,...,0.328,149.536,audio_features,5ehN5A3B3lDwmFCYO63Wk6,spotify:track:5ehN5A3B3lDwmFCYO63Wk6,https://api.spotify.com/v1/tracks/5ehN5A3B3lDw...,https://api.spotify.com/v1/audio-analysis/5ehN...,235053,5,I'd put the whiskey back in the bottle\nPut th...
822,23,Chayce Beckham,spotify:artist:5ujvZU2thXjZgFKPUt1rDt,61,modern country pop,228144,2021-05-14,82,0.626,0.583,...,0.428,87.977,audio_features,1ZpPaBDswjV3VSUKqLDXPE,spotify:track:1ZpPaBDswjV3VSUKqLDXPE,https://api.spotify.com/v1/tracks/1ZpPaBDswjV3...,https://api.spotify.com/v1/audio-analysis/1ZpP...,228145,4,Simple as my mama said when I was very young\n...

In [29]:
temiz_veri_seti = pd.read_csv('temizlenmis_dosya_adı.csv')
temiz_veri_seti_alfabetik = temiz_veri_seti.sort_values(by='Track Name')
temiz_veri_seti_alfabetik.to_csv('temizlenmis_dosya_adı_alfabestik.csv', index=False)